### ISSUE TITLE
Is it possible to share the dataset？

### ISSUE THREAD

**Issue by keepfighting666** [lewuu/SCDUNetPP#1]
Hello, may I request permission to share the dataset used in the paper for the sole purpose of replicating and learning? Thank you.

**Comment by babangain** [comment]
Same Request.

**Comment by joe-vettek** [comment]
@lewuu Thank you for your generous code sharing spirit, but I am still worried that it is difficult to build the correct dataset here. I don’t know if it is possible to share the model or dataset (part of it is also very grateful).

**Comment by Victoria-Song992** [comment]
@lewuu Thank you for generously sharing your code, but I'm still concerned about the difficulty of accurately constructing the required dataset. Could you possibly share part of the dataset? It would be greatly appreciated.

**Comment by lewuu** [comment]
Thanks for your interest, the data samples have been added to the repository.
