### ISSUE TITLE
您好，最近有幸拜读了您在jag上的论文，请问您能否提供完整的数据集呢，目前的仓库中似乎只包含一张128x128x23的数据

### ISSUE THREAD

**Issue by fsqy-zhang** [lewuu/SCDUNetPP#2]
您好，最近有幸拜读了您在jag上的论文，请问您能否提供完整的数据集呢，目前的仓库中似乎只包含一张128x128x23的数据

**Comment by lewuu** [comment]
您好，非常抱歉，完整的数据集在短时间内无法提供，后续可能会更新至仓库。目前仓库中已经上传了数据和标签的示例，您可以根据论文中给出的数据处理流程制作自己的数据集。感谢您的理解！
